[dependencies]
async-std = "1.10"
use async_std::net::TcpStream;
use std::io::{self, Write};

async fn fetch_data() -> io::Result<()> {
    let stream = TcpStream::connect("127.0.0.1:8080").await?;
    
    writeln!(stream, "GET /").await?;
    Ok(())
}

fn main() {
    async_std::task::block_on(fetch_data()).unwrap();
}
